data:
  train_data_path: "/kaggle/input/lmsys-chatbot-arena/train.csv"
  test_data_path: "/kaggle/input/lmsys-chatbot-arena/test.csv"
  prompt: "prompt"
  resp_a: "response_a"
  resp_b: "response_b"
  resp_a_win: "winner_model_a"
  resp_b_win: "winner_model_b"
  resp_tie: "winner_tie"
  added_target_field: "labels"

pipeline_embedding_w2v:
  model_name: "glove-twitter-50"
  model_path: "/kaggle/working/w2v_models/w2v_glove-twitter-50"
  embedding_aggregator: "mean"

pipeline_embedding_deberta:
  tokenizer_name: "microsoft/deberta-base"
  model_name: "microsoft/deberta-base"
  tokenizer_output_path: "/kaggle/working/model_output/"
  model_output_path: "/kaggle/working/model_output/"
  max_prompt_token_length: 64
  max_resp_a_token_length: 255
  max_resp_b_token_length: 255

classifier_lgbm_pipeline:
  lgbm:
    params:
        n_estimators: 1000
        max_depth: 4
        subsample: 0.8
        colsample_bytree: 0.8
        objective: "multiclass"
        num_class: 3
        metric: "multi_logloss"
        random_state: 123
        learning_rate: 0.003
    eval_pct: 0.2
    early_stopping: 100
  seed: 123
  output_path: "/kaggle/working/lgbm_model.pkl"
